language: python
python: "3.8"

env:
  global:
    CC_TEST_REPORTER_ID=d10006907feb88133c59b48126926b89f7f03023db3de83fb537c23e4791b052

before_install:
  - pip install poetry

# command to install dependencies
install: make

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to run tests
script:
  - make lint
  - make tests

after_script:
  - ./cc-test-reporter after-build -t coverage.py -d --exit-code $TRAVIS_TEST_RESULT