name: Python build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:    
    # set up python
    - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    # run linter
    - name: Lint with flake8
      run:
        pip install poetry
        make install
        make lint  
    # run pytest
    - name: Test with pytest
      run:
        pip install poetry
        make install
        make lint